#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export OPENTALKING_UNIFIED_HOST="${OPENTALKING_UNIFIED_HOST:-0.0.0.0}"
export OPENTALKING_UNIFIED_PORT="${OPENTALKING_UNIFIED_PORT:-8010}"
export OPENTALKING_AVATARS_DIR="${OPENTALKING_AVATARS_DIR:-./examples/avatars}"
export OPENTALKING_TORCH_DEVICE="${OPENTALKING_TORCH_DEVICE:-cuda}"
export OPENTALKING_MODELS_DIR="${OPENTALKING_MODELS_DIR:-$ROOT/models}"
export OPENTALKING_RESET_FRAME_IDX_ON_SPEAK="${OPENTALKING_RESET_FRAME_IDX_ON_SPEAK:-1}"
export OPENTALKING_WAV2LIP_LIVE_MODE="${OPENTALKING_WAV2LIP_LIVE_MODE:-streaming}"
export OPENTALKING_WAV2LIP_RENDER_CHUNK_MS="${OPENTALKING_WAV2LIP_RENDER_CHUNK_MS:-200}"
export PYTHONPATH="$ROOT/src:$ROOT/apps/unified/src${PYTHONPATH:+:$PYTHONPATH}"

PYTHON_BIN="${OPENTALKING_PYTHON_BIN:-python}"
DEBUG_DUMP_DIR="${OPENTALKING_DEBUG_DUMP_SPEECH_DIR:-}"

if [[ -n "$DEBUG_DUMP_DIR" ]]; then
  export OPENTALKING_DEBUG_DUMP_SPEECH_DIR="$DEBUG_DUMP_DIR"
  mkdir -p "$DEBUG_DUMP_DIR"
fi

exec "$PYTHON_BIN" -m apps.unified.main "$@"
